In [1]:
import numpy as np

# Create an array of 10 zeros
zeros_array = np.zeros(10)

# Create an array of 10 ones
ones_array = np.ones(10)

# Create an array of 10 fives
fives_array = np.full(10, 5)

# Print the arrays
print("An array of 10 zeros:")
print(zeros_array)
print("An array of 10 ones:")
print(ones_array)
print("An array of 10 fives:")
print(fives_array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5 5 5 5 5 5 5 5 5 5]
