In [1]:
import numpy as np

# Create an array with values from 2 to 10 and reshape it into a 3x3 matrix
matrix_3x3 = np.arange(2, 11).reshape(3, 3)

# Print the 3x3 matrix
print(matrix_3x3)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
