In [1]:
import numpy as np

# Define a list
my_list = [1, 2, 3, 4, 5, 6, 7, 8]

# Define a tuple containing two lists
my_tuple = ([8, 4, 6], [1, 2, 3])

# Convert the list to a NumPy array
list_to_array = np.array(my_list)

# Convert the tuple to a NumPy array
tuple_to_array = np.array(my_tuple)

# Print the arrays
print("List to array:")
print(list_to_array)
print("Tuple to array:")
print(tuple_to_array)

List to array:
[1 2 3 4 5 6 7 8]
Tuple to array:
[[8 4 6]
 [1 2 3]]
