In [1]:
# Q. Splitting sales data into quarterly reports

import numpy as np

# Given sales data in thousands of dollars
monthly_sales = np.array([120, 135, 148, 165, 180, 155, 168, 190, 205, 198, 210, 225])

# Splitting sales into quarters (assuming data starts from Q1)
quarters = np.array_split(monthly_sales, 4)

for i, quarter in enumerate(quarters, 1):
    print(f"Quarter {i} Sales (in thousands of dollars):\n {quarter}\n")

Quarter 1 Sales (in thousands of dollars):
 [120 135 148]

Quarter 2 Sales (in thousands of dollars):
 [165 180 155]

Quarter 3 Sales (in thousands of dollars):
 [168 190 205]

Quarter 4 Sales (in thousands of dollars):
 [198 210 225]

